# Generated by Django 6.0.1 on 2026-01-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Навык',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=100, verbose_name='Название')),
                ('уровень', models.IntegerField(default=70, verbose_name='Уровень (0-100)')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Проект',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=150, verbose_name='Название')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('стек', models.CharField(blank=True, max_length=200, verbose_name='Стек технологий')),
                ('github', models.URLField(blank=True, verbose_name='GitHub ссылка')),
                ('demo', models.URLField(blank=True, verbose_name='Demo ссылка')),
                ('картинка', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Профиль',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('имя', models.CharField(max_length=100, verbose_name='Имя')),
                ('должность', models.CharField(default='Python-разработчик', max_length=120, verbose_name='Должность')),
                ('описание', models.TextField(blank=True, verbose_name='О себе')),
                ('фото', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото')),
                ('город', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('телефон', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='СоцСеть',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=50, verbose_name='Название')),
                ('ссылка', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Соцсеть',
                'verbose_name_plural': 'Соцсети',
            },
        ),
    ]
