# Generated by Django 6.0.1 on 2026-01-28 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Язык')),
                ('level', models.CharField(max_length=80, verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='ФИО')),
                ('role', models.CharField(default='Python Backend Developer', max_length=120, verbose_name='Профессия')),
                ('city', models.CharField(default='Ташкент, Узбекистан', max_length=120, verbose_name='Город')),
                ('about', models.TextField(blank=True, verbose_name='Обо мне')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название проекта')),
                ('stack', models.CharField(blank=True, max_length=200, verbose_name='Стек')),
                ('date_text', models.CharField(blank=True, max_length=120, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub ссылка')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Навык')),
                ('level', models.IntegerField(default=70, verbose_name='Уровень (0-100)')),
            ],
        ),
        migrations.DeleteModel(
            name='Навык',
        ),
        migrations.DeleteModel(
            name='Проект',
        ),
        migrations.DeleteModel(
            name='Профиль',
        ),
        migrations.DeleteModel(
            name='СоцСеть',
        ),
    ]
