# Generated by Django 6.0.1 on 2026-01-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_contactlink_hobby_remove_language_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LeftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст')),
                ('instagram', models.CharField(blank=True, max_length=200, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=200, verbose_name='Telegram')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactLink',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_text',
            field=models.TextField(blank=True, verbose_name='Текст резюме'),
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(blank=True, max_length=200, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Язык 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_1_stars',
            field=models.IntegerField(default=5, verbose_name='Звёзды 1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Язык 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_2_stars',
            field=models.IntegerField(default=4, verbose_name='Звёзды 2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='Язык 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language_3_stars',
            field=models.IntegerField(default=3, verbose_name='Звёзды 3'),
        ),
        migrations.AddField(
            model_name='profile',
            name='qualification',
            field=models.CharField(blank=True, max_length=150, verbose_name='Квалификация'),
        ),
    ]
