# Generated by Django 6.0.1 on 2026-01-31 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_adminuser_leftblock_delete_contactlink_delete_hobby_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
        migrations.DeleteModel(
            name='LeftBlock',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_text',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hobbies',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_1_stars',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_2_stars',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language_3_stars',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='qualification',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
