# Generated by Django 6.0.1 on 2026-01-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_delete_adminuser_delete_leftblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='Через запятую: Python, Django, HTML...'),
        ),
    ]
